Repository jitacm/30_days_c_-C-Server-, pull requests merged in 2025-08, with the labels that each got.

#2 Bugs fixed and added core Features #1
  C-Server/Http_server.c
  C-Server/Makefile/Makefile
  C-Server/www/404.html
  C-Server/www/index.html
Labels: bug, 30daysdevchallenge, jitacm, feature, level-2

#4 Add Professional Project Documentation (README.md)
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#9 Documentation Upgrade: Full-Scale README Overhaul with Detailed Architecture and Usage Instructions #8
  C-Server/Http_server.c
  README.md
Labels: documentation, 30daysdevchallenge, jitacm, level-2

#5 enhance UI and add multithreading
  30_days_c_-C-Server-/C-Server/Http_server.c
  30_days_c_-C-Server-/C-Server/Makefile/Makefile
  30_days_c_-C-Server-/C-Server/server
  30_days_c_-C-Server-/C-Server/server.log
  30_days_c_-C-Server-/C-Server/www/404.html
  30_days_c_-C-Server-/C-Server/www/index.html
  30_days_c_-C-Server-/C-Server/www/style.css
  30_days_c_-C-Server-/README.md
  Py/30-days-Python-Attack-Defense/Attack_defence-game/Attack_game.py
  Py/30-days-Python-Attack-Defense/Attack_defence-game/assets/P1_Shot.png
  Py/30-days-Python-Attack-Defense/Attack_defence-game/assets/P2_Shot.png
  Py/30-days-Python-Attack-Defense/Attack_defence-game/attack_with_bot.py
  Py/30-days-Python-Attack-Defense/README.md
Labels: 30daysdevchallenge, jitacm, feature, level-4

#11 Feature: Implementing Dynamic Routing and POST/HEAD Support #10
  C-Server/Http_server.c
  C-Server/Makefile/Makefile
  C-Server/www/index.html
  C-Server/www/style.css
Labels: 30daysdevchallenge, jitacm, feature, level-3
